# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: settings_reset
  # - board: nice_nano_v2
  #   shield: cradio_left
  # - board: nice_nano_v2
  #   shield: cradio_right
  # - board: nice_nano_v2
  #   shield: batta_left
  # - board: nice_nano_v2
  #   shield: batta_right
  # - board: nice_nano_v2
  #   shield: battamini_left
  # - board: nice_nano_v2
  #   shield: battamini_right
  - board: nice_nano_v2
    shield: battoota_left
  - board: nice_nano_v2
    shield: battoota_right
  - board: nice_nano_v2
    shield: battootaone_left
  - board: nice_nano_v2
    shield: battootaone_right
  - board: nice_nano_v2
    shield: basbousa_left
  - board: nice_nano_v2
    shield: basbousa_right