# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: settings_reset
  - board: nice_nano_v2
    shield: wizza_left
  - board: nice_nano_v2
    shield: wizza_right
  - board: nice_nano_v2
    shield: wizzav2_left
  - board: nice_nano_v2
    shield: wizzav2_right
  - board: nice_nano_v2
    shield: wizzades_left
  - board: nice_nano_v2
    shield: wizzades_right
  - board: nice_nano_v2
    shield: asfoora
  # - board: seeeduino_xiao_ble
  #   shield: keywell_left
  # - board: seeeduino_xiao_ble
  #   shield: keywell_right
