manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
  #  - name: sadekbaroudi
  #    url-base: https://github.com/sadekbaroudi
    - name: inorichi
      url-base: https://github.com/inorichi
  projects:
    - name: zmk
      remote: petejohanson
      revision: d45cb3c26fc113357dfc035965e51c84e13e218d #pmw3610 trackball issue
      import: app/west.yml
    - name: chiptuner-zmk-module
      remote: petejohanson
      revision: main
    - name: zmk-pmw3610-driver
      remote: inorichi
      revision: main
    # replace the one above with the commented one below when it gets merged into zmk
    # must swap the zmk-fingerpunch-keyboards repo as well at the same time
    # - name: zmk
    #   remote: zmkfirmware
    #   revision: main
    #   import: app/west.yml
  self:
    path: config
